### PR TITLE
Handle Symbols

### PR DESCRIPTION
**Pull request by bruce-one**
Currently Icepick doesn't clone Symbol keys in objects.

This PR adds support for doing so.

Some tests were added, but possibly not enough.

I added the tests in a separate file to avoid syntax issues when computed properties aren't supported. I also bumped the jscs version to ensure it handled ES6 syntax.

(No problem if you don't want this, or want it handled differently in some way, it just fixed my issue (which surprised/trapped me) so I thought I'd make a PR :-) )

### CODE REVIEW

**Comment by aearly** [comment]
What kind of data do you have that uses Symbols for property names?  Just curious about the use case for this.

**Comment by bruce-one** [comment]
I'm actually using it for adding some "hidden" keys to existing JSON data structures (eg date loaded, or if still loading, etc).

It doesn't need to be Symbols - and could be a bad use, truth be told - but... I dunno, it's how I did it :-p

It's also done in a few situations where there are keys for data that are set by other systems (and hence could be anything), but I don't want it to clash with the values stored under the Symbols.

It's not the most important thing ever (read as: feel free not to merge this :-) ) but it's a bit of a trap because `i.assign({ [SOME_SYMBOL]: 1 }, { a: 'b'}) === { a: 'b' }` because icepick removes the symbol value - whilst `Object.assign({ [SOME_SYMBOL]: 1 }, { a: 'b' }) === { [SOME_SYMBOL]: 1, a: 'b' }`.

And I'd just assumed that `i.assign` would work like `Object.assign`.

**Comment by aearly** [comment]
I'm going to close this for now.  I'd rather not slow the the library down by making getting the properties of an object more complicated than `Object.keys()`.  In the future, when ES6 is more universal, we can probably use something like [`Reflect.ownKeys`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/ownKeys) to get both standard props and Symbol props in a single step.

**Comment by bruce-one** [comment]
👍 

No problem :-)

Just in case anyone encounters something similar, I ended up adding:

    i.extend = i.assign = function overridden(...args) {
        return i.freeze(Object.assign(Object.create(null), ...args))
    }

to override `i.assign`, because the inconsistency between `Object.assign` and `i.assign` kept trapping me... (Which helped me a lot :-) )

**Pull request closed without merging**
